services:
  odoo-db:
    image: postgres:15
    container_name: odoo-database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=Password@123
    volumes:
      - ./odoo-system/data/db:/var/lib/postgresql/data
    networks:
      - central-network

  odoo-server:
    image: odoo:18.0
    container_name: odoo-server
    restart: always
    depends_on:
      - odoo-db
    ports:
      - "9069:8069"
    volumes:
      - ./odoo-system/data/filestore:/var/lib/odoo
      - ./odoo-system/config:/etc/odoo
      - ./odoo-system/addons:/mnt/extra-addons
    environment:
      - HOST=odoo-database
      - USER=odoo
      - PASSWORD=Password@123
    networks:
      - central-network


  mautic-db:
    image: mariadb:10.11
    container_name: mautic-database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MauticRootPass!123
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic_user
      - MYSQL_PASSWORD=Mautic@123
    volumes:
      - ./mautic-system/data/db:/var/lib/mysql
    networks:
      - central-network

  mautic-server:
    image: mautic/mautic:latest
    container_name: mautic-server
    restart: always
    depends_on:
      - mautic-db
    ports:
      - "8014:80"
    volumes:
      #- ./mautic-system/data/html:/var/www/html
      - ./mautic-system/data/html_logs:/var/www/html/var/logs
    environment:
      - MAUTIC_DB_HOST=mautic-database
      - MAUTIC_DB_USER=mautic_user
      - MAUTIC_DB_PASSWORD=Mautic@123
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_HEZE_MODE=false
      - MAUTIC_WEBROOT=/var/www/html
    networks:
      - central-network

networks:
  central-network:
    driver: bridge
