[options]
admin_passwd = $pbkdf2-sha512$600000$co6x1lorJeQ8ZyyldI5Rqg$81WxoKLCKRfZk6i4JNq17lajdIov6k8Q76VxyR.XdR9vYEzx5nb2BHapJQYxS8ohoHd36olwz3EReK079uG27g
db_host = odoo-db
db_port = 5432
db_user = odoo
db_password = Password@123
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
http_port = 8069
proxy_mode = True

